---

- name: create a directory for node exporter
  file:
    path: /root/node_exporter
    mode: 0755
    group: root
    owner: root
    state: directory


- name: Extract Node Exporter
  unarchive:
    dest: /root/node_exporter/node_exporter-1.5.0.linux-amd64
    src: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    remote_src: yes



- name: Create the Node Exporter service
  copy:
    src: ./files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service


- name: start and enable service
  systemd:
    name: node_exporter.service
    enabled: yes
    state: started




