version: '3.7'


services:

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - ./alertmanager_data:/alertmanager
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager_config.yaml'
      - '--storage.path=/alertmanager'
    deploy:
      mode: global


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    privileged: true
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=remote-write-receiver'
#    network_mode: host
    ports:
      - 9090:9090
    restart: always

#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

  node-exporter:
    image: prom/node-exporter:latest
    privileged: true
    volumes:
      - /:/host:ro
    command:
      - "--path.rootfs=/host"
    restart: always
    network_mode: host

    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    volumes: 
      - ./config:/config
    privileged: true
    restart: always
    network_mode: host
    command: --config.file=/config/blackbox.yml
    #ports:
    #  - 9115:9115

#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
#      - ./grafana/provisioning/:/etc/grafana/provisioning/
#      - ./grafana_conf:/usr/share/grafana/conf

#  pushgateway:
#    image: prom/pushgateway
#    restart: always
#    expose:
#      - 9091
#    ports:
#      - "9091:9091"
#    networks:
#      - back-tier